# some roots (i.e. fract/frag or tac/tic) have the same definition
# make certain words possible to have two (2) guesses

roots = {
    "ab": "away",
    "ambi": "both",
    "ambul": "move or walk",
    "ami": "love",
    "contra": "against",
    "cred": "believe",
    "crypt": "hidden",
    "cycl": "circle or ring",
    "dem": "people",
    "derm": "skin",
    "dict": "speak",
    "domin": "master",
    "dur": "hard",
    "ego": "I, self",
    "esth": "feeling",
    "extra": "outside",
    "fid": "faith",
    "flect": "bend",
    "flor": "flower",
    "fract": "break",
    "frag": "break",
    "fug": "run away",
    "gen": "birth, production",
    "gram": "something written",
    "graph": "to write",
    "grat": "pleasing",
    "gress": "to step, to go",
    "hetero": "different",
    "homo": "same",
    "idio": "peculiar, distict",
    "judi": "judge, lawyer",
    "ling": "language",
    "loqu": "speak",
    "magn": "large, great",
    "mal": "bad",
    "mut": "change",
    "ob": "against",
    "phil": "love",
    "plac": "calm",
    "re": "back, again",
    "sagac": "wise",
    "sang": "having to do with blood",
    "sequ": "follow",
    "somn": "sleep",
    "tac": "be silent",
    "tic": "be silent",
    "troph": "feed, grow",
    "ultim": "last",
    "vener": "respectful",
    "vit": "life",
    "voc": "voice",
    "vol": "fly, wish"
}
