words = {
    "abject": "to describe negative things and heighten the negativity; describes the highest level of loneliness, "
              "poverty, or sadness a person could reach",
    "abode": "a place where people live",
    "abstract": "not concrete or tangible; might exist as an idea only or might be something that you can touch but "
                "that represents ideas or feelings",
    "acknowledge": "to notice someone or something and make sure it knows that it has been noticed",
    "adapt": "to change to fit the situation",
    "admonition": "the scolding one might receive if one has done something wrong",
    "affluent": "to be very well off financially",
    "agitate": "to work up; to disturb",
    "aggrandize": "to make something grander",
    "aggregate": "to build up parts to create a whole",
    "alternation": "to take turns",
    "amicable": "characterized by friendly goodwill",
    "analogous": "similar or comparable to something else",
    "analogy": "a comparison between two items using 'like' or 'as'",
    "anomaly": "something strange or out of the usual pattern of things",
    "antipathy": "a strong feeling of dislike",
    "apparition": "something that suddenly appears",
    "arbitrary": "random",
    "ascertain": "to find out or learn with certainty",
    "aspire": "to seek to attain or accomplish a particular goal",
    "autocratic": "to describe someone who is acting like someone in charge who has all the power (an autocrat)",
    "automated": "something has been change to make it now automatic where as previously it was not",
    "beget": "to produce especially as an effect or outgrowth",
    "benevolent": "kind",
    "bestow": "to give something to someone",
    "biological": "describing something related to the study of life or related to life itself",
    "calibrate": "to adjust something so that it runs the way it should",
    "calisthenics": "a type of exercise that rely on body weight",
    "capacity": "a measure of something's ability",
    "celestial": "of or relating to outer space",
    "censure": "to give someone a formal reprimand",
    "circulation": "anything moving back and form or around in a predictable pattern",
    "coerce": "to get someone to do something by threat of force.",
    "cognition": "the ability to understand something",
    "colloquial": "used in or characteristic of familiar and informal conversation",
    "commercial": "occupied with or engaged in commerce or work intended for commerce",
    "complementary": "serving to fill out or complete",
    "complimentary": "something that is provided free of charge",
    "conflate": "to combine things into a composite whole",
    "conjure": "to bring something up",
    "consensus": "when everyone agrees",
    "consequence": "the result of an action taken",
    "conservator": "a person whose job is to conserve or preserve something",
    "constitution": "the basic principles and laws of a nation, state, or social group that determines the powers and "
                    "duties of the government and guarantees certain rights to the people in it;\nsomeone's bodily "
                    "health; how something is put together",
    "contingent": "relying on other factors to come to be",
    "conventional": "of the traditional rules that are set up",
    "convey": "to get something across",
    "convoke": "to call a meeting",
    "convulsion": "an abnormal violent and involuntary contraction or series of contractions of the muscles",
    "cooperatively": "working in a cooperative manner",
    "cultivate": "to bring something up; to try to make it grow or exist",
    "dawdle": "to lag behind",
    "decipher": "to figure something out",
    "deficient": "lacking in some necessary quality or element",
    "degrade": "to break something down slowly over time",
    "demur": "to politely say no to something or avoid it",
    "desolation": "total abandonment, emptiness, and destruction",
    "despoil": "to take away anything of value",
    "deter": "to stop someone from doing something",
    "disenfranchise": "to take away someone's right to vote; to prevent them from using it",
    "disparity": "an inequality or a difference between two things",
    "disseminate": "to pass out something; to ensure the spread of it",
    "dissimilar": "not similar",
    "diverge": "to move apart",
    "doctrine": "a sincerely held belief (often of the religious variety, but also political or other beliefs as well)",
    "doldrums": "a time in which nothing happens",
    "domestic": "of or relating to the home",
    "dominion": "control or authority over someone or something",
    "dubious": "doubtful and uncertain",
    "earnest": "characterized by an intense and serious state of mind",
    "eddy": "when water or air moves swiftly in a circular motion",
    "effectual": "able to produce a desired effect",
    "efficacy": "the effectiveness of something",
    "efficient": "capable of producing desired results with little to no waste (as of time or materials)",
    "embellish": "to add details or flair to something",
    "emit": "to give off",
    "empathize": "to know what someone is feeling",
    "endearing": "arousing feelings of affection or admiration",
    "endeavor": "to try something; a try",
    "endow": "to give",
    "enhance": "to make something better or clearer",
    "enterprise": "a project or undertaking that is especially difficult, complicated, or risky",
    "entice": "to convince someone to do something through the promice of reward",
    "entrenched": "firmly established and difficult or unlikely to change; ingrained",
    "ephemeral": "lasting a very short time",
    "evince": "to show one's feelings",
    "expenditure": "a spending of money or other resources",
    "explanatory": "serving to explain",
    "extensive": "widespread or far-reaching",
    "feature": "a part of an item that is designed for a specific use",
    "feeble": "weak",
    "fetter": "to hold someone or something back from what they want to do or accomplish",
    "finite": "having a definitive beginning and ending",
    "fiscal": "of or relating to money and the economy",
    "florid": "(describing a person's face) red or flushed",
    "former": "the one before or in the past",
    "forum": "a location or a meeting where people can talk about their thoughts, ideas, and opinions",
    "frantic": "desperate",
    "frequent": "often",
    "fundamental": "the basics",
    "germinate": "to take something with potential and make it start ot grow",
    "glom": "to attack to something (often in a blob-like manner)",
    "glut": "a ridiculous abundance of something",
    "grievance": "a complaint",
    "haggle": "to bargain or wrangle",
    "ignominious": "undignified",
    "illegible": "unable to be read or understood",
    "immured": "kept as a prisoner; closed away and out of sight",
    "impel": "to push or force someone to do something in some way",
    "inapplicable": "irrelevant",
    "incomprehensible": "impossible to comprehend; unintelligible",
    "incontestable": "indisputable",
    "incorporate": "to fully include something",
    "incredulous": "unwilling to admit or accept what is offered as true; skeptical",
    "indifference": "absense of compulsion to or toward one thing or another",
    "indistiguishable": "not distinguishable",
    "ineffective": "not capable of performing efficiently or as expected",
    "inefficacious": "not having the desired effect",
    "inexorable": "inevitable",
    "ingenious": "genius",
    "innumerable": "unable to be counted",
    "institution": "an organization that has been created to fulfill a purpose",
    "insurrection": "a revolt; an uprising",
    "integrate": "to form, coordinate, or blend into a functioning or unified whole",
    "intend": "to have in mind as a purpose or goal"}
# 125 words / 250
