words = {
    "abject": "to describe negative things and heighten the negativity; describes the highest level of loneliness, "
              "poverty, or sadness a person could reach",
    "abode": "a place where people live",
    "abstract": "not concrete or tangible; might exist as an idea only or might be something that you can touch but "
                "that represents ideas or feelings",
    "acknowledge": "to notice someone or something and make sure it knows that it has been noticed",
    "adapt": "to change to fit the situation",
    "admonition": "the scolding one might receive if one has done something wrong",
    "affluent": "to be very well off financially",
    "agitate": "to work up; to disturb",
    "aggrandize": "to make something grander",
    "aggregate": "to build up parts to create a whole",
    "alternation": "to take turns",
    "amicable": "characterized by friendly goodwill",
    "analogous": "similar or comparable to something else",
    "analogy": "a comparison between two items using 'like' or 'as'",
    "anomaly": "something strange or out of the usual pattern of things",
    "antipathy": "a strong feeling of dislike",
    "apparition": "something that suddenly appears",
    "arbitrary": "random",
    "ascertain": "to find out or learn with certainty",
    "aspire": "to seek to attain or accomplish a particular goal",
    "autocratic": "to describe someone who is acting like someone in charge who has all the power (an autocrat)",
    "automated": "something has been change to make it now automatic where as previously it was not",
    "beget": "to produce especially as an effect or outgrowth",
    "benevolent": "kind",
    "bestow": "to give something to someone",
    "biological": "describing something related to the study of life or related to life itself",
    "calibrate": "to adjust something so that it runs the way it should",
    "calisthenics": "a type of exercise that rely on body weight",
    "capacity": "a measure of something's ability",
    "celestial": "of or relating to outer space",
    "censure": "to give someone a formal reprimand",
    "circulation": "anything moving back and form or around in a predictable pattern",
    "coerce": "to get someone to do something by threat of force.",
    "cognition": "the ability to understand something",
    "colloquial": "used in or characteristic of familiar and informal conversation",
    "commercial": "occupied with or engaged in commerce or work intended for commerce",
    "complementary": "serving to fill out or complete",
    "complimentary": "something that is provided free of charge",
    "conflate": "to combine things into a composite whole",
    "conjure": "to bring something up",
    "consensus": "when everyone agrees",
    "consequence": "the result of an action taken",
    "conservator": "a person whose job is to conserve or preserve something",
    "constitution": "the basic principles and laws of a nation, state, or social group that determines the powers and "
                    "duties of the government and guarantees certain rights to the people in it;\nsomeone's bodily "
                    "health; how something is put together",
    "contingent": "relying on other factors to come to be",
    "conventional": "of the traditional rules that are set up",
    "convey": "to get something across",
    "convoke": "to call a meeting",
    "convulsion": "an abnormal violent and involuntary contraction or series of contractions of the muscles",
    "cooperatively": "working in a cooperative manner",
    "cultivate": "to bring something up; to try to make it grow or exist",
    "dawdle": "to lag behind",
    "decipher": "to figure something out",
    "deficient": "lacking in some necessary quality or element",
    "degrade": "to break something down slowly over time",
    "demur": "to politely say no to something or avoid it",
    "desolation": "total abandonment, emptiness, and destruction",
    "despoil": "to take away anything of value",
    "deter": "to stop someone from doing something",
    "disenfranchise": "to take away someone's right to vote; to prevent them from using it",
    "disparity": "an inequality or a difference between two things",
    "disseminate": "to pass out something; to ensure the spread of it",
    "dissimilar": "not similar",
    "diverge": "to move apart",
    "doctrine": "a sincerely held belief (often of the religious variety, but also political or other beliefs as well",
    "doldrums": "a time in which nothing happens",
    "domestic": "of or relating to the home",
    "dominion": "control or authority over someone or something",
    "dubious": "doubtful and uncertain",
    "earnest": "characterized by an intense and serious state of mind",
    "eddy": "when water or air moves swiftly in a circular motion",
    "effectual": "able to produce a desired effect",
    "efficacy": "the effectiveness of something",
    "efficient": "capable of producing desired results with little to no waste (as of time or materials)",
    "embellish": "to add details or flair to something"}
# 75 words / 250
