words = {
    "abject": "to describe negative things and heighten the negativity; describes the highest level of loneliness, "
              "poverty, or sadness a person could reach",
    "abode": "a place where people live",
    "abstract": "not concrete or tangible; might exist as an idea only or might be something that you can touch but "
                "that represents ideas or feelings",
    "acknowledge": "to notice someone or something and make sure it knows that it has been noticed",
    "adapt": "to change to fit the situation",
    "admonition": "the scolding one might receive if one has done something wrong",
    "affluent": "to be very well off financially",
    "agitate": "to work up; to disturb",
    "aggrandize": "to make something grander",
    "aggregate": "to build up parts to create a whole",
    "alternation": "to take turns",
    "amicable": "characterized by friendly goodwill",
    "analogous": "similar or comparable to something else",
    "analogy": "a comparison between two items using 'like' or 'as'",
    "anomaly": "something strange or out of the usual pattern of things",
    "antipathy": "a strong feeling of dislike",
    "apparition": "something that suddenly appears",
    "arbitrary": "random",
    "ascertain": "to find out or learn with certainty",
    "aspire": "to seek to attain or accomplish a particular goal",
    "autocratic": "to describe someone who is acting like someone in charge who has all the power (an autocrat)",
    "automated": "something has been change to make it now automatic where as previously it was not",
    "beget": "to produce especially as an effect or outgrowth",
    "benevolent": "kind",
    "bestow": "to give something to someone",
    "biological": "describing something related to the study of life or related to life itself",
    "calibrate": "to adjust something so that it runs the way it should",
    "calisthenics": "a type of exercise that rely on body weight",
    "capacity": "a measure of something's ability",
    "celestial": "of or relating to outer space",
    "censure": "to give someone a formal reprimand",
    "circulation": "anything moving back and form or around in a predictable pattern",
    "coerce": "to get someone to do something by threat of force.",
    "cognition": "the ability to understand something",
    "colloquial": "used in or characteristic of familiar and informal conversation",
    "commercial": "occupied with or engaged in commerce or work intended for commerce",
    "complementary": "serving to fill out or complete",
    "complimentary": "something that is provided free of charge",
    "conflate": "to combine things into a composite whole",
    "conjure": "to bring something up",
    "consensus": "when everyone agrees",
    "consequence": "the result of an action taken",
    "conservator": "a person whose job is to conserve or preserve something",
    "constitution": "the basic principles and laws of a nation, state, or social group that determines the powers and "
                    "duties of the government and guarantees certain rights to the people in it;\nsomeone's bodily "
                    "health; how something is put together",
    "contingent": "relying on other factors to come to be",
    "conventional": "of the traditional rules that are set up",
    "convey": "to get something across",
    "convoke": "to call a meeting",
    "convulsion": "an abnormal violent and involuntary contraction or series of contractions of the muscles",
    "cooperatively": "working in a cooperative manner",
    "cultivate": "to bring something up; to try to make it grow or exist",
    "dawdle": "to lag behind",
    "decipher": "to figure something out",
    "deficient": "lacking in some necessary quality or element",
    "degrade": "to break something down slowly over time",
    "demur": "to politely say no to something or avoid it",
    "desolation": "total abandonment, emptiness, and destruction",
    "despoil": "to take away anything of value",
    "deter": "to stop someone from doing something",
    "disenfranchise": "to take away someone's right to vote; to prevent them from using it",
    "disparity": "an inequality or a difference between two things",
    "disseminate": "to pass out something; to ensure the spread of it",
    "dissimilar": "not similar",
    "diverge": "to move apart",
    "doctrine": "a sincerely held belief (often of the religious variety, but also political or other beliefs as well)",
    "doldrums": "a time in which nothing happens",
    "domestic": "of or relating to the home",
    "dominion": "control or authority over someone or something",
    "dubious": "doubtful and uncertain",
    "earnest": "characterized by an intense and serious state of mind",
    "eddy": "when water or air moves swiftly in a circular motion",
    "effectual": "able to produce a desired effect",
    "efficacy": "the effectiveness of something",
    "efficient": "capable of producing desired results with little to no waste (as of time or materials)",
    "embellish": "to add details or flair to something",
    "emit": "to give off",
    "empathize": "to know what someone is feeling",
    "endearing": "arousing feelings of affection or admiration",
    "endeavor": "to try something; a try",
    "endow": "to give",
    "enhance": "to make something better or clearer",
    "enterprise": "a project or undertaking that is especially difficult, complicated, or risky",
    "entice": "to convince someone to do something through the promice of reward",
    "entrenched": "firmly established and difficult or unlikely to change; ingrained",
    "ephemeral": "lasting a very short time",
    "evince": "to show one's feelings",
    "expenditure": "a spending of money or other resources",
    "explanatory": "serving to explain",
    "extensive": "widespread or far-reaching",
    "feature": "a part of an item that is designed for a specific use",
    "feeble": "weak",
    "fetter": "to hold someone or something back from what they want to do or accomplish",
    "finite": "having a definitive beginning and ending",
    "fiscal": "of or relating to money and the economy",
    "florid": "(describing a person's face) red or flushed",
    "former": "the one before or in the past",
    "forum": "a location or a meeting where people can talk about their thoughts, ideas, and opinions",
    "frantic": "desperate",
    "frequent": "often",
    "fundamental": "the basics",
    "germinate": "to take something with potential and make it start ot grow",
    "glom": "to attack to something (often in a blob-like manner)",
    "glut": "a ridiculous abundance of something",
    "grievance": "a complaint",
    "haggle": "to bargain or wrangle",
    "ignominious": "undignified",
    "illegible": "unable to be read or understood",
    "immured": "kept as a prisoner; closed away and out of sight",
    "impel": "to push or force someone to do something in some way",
    "inapplicable": "irrelevant",
    "incomprehensible": "impossible to comprehend; unintelligible",
    "incontestable": "indisputable",
    "incorporate": "to fully include something",
    "incredulous": "unwilling to admit or accept what is offered as true; skeptical",
    "indifference": "absense of compulsion to or toward one thing or another",
    "indistiguishable": "not distinguishable",
    "ineffective": "not capable of performing efficiently or as expected",
    "inefficacious": "not having the desired effect",
    "inexorable": "inevitable",
    "ingenious": "genius",
    "innumerable": "unable to be counted",
    "institution": "an organization that has been created to fulfill a purpose",
    "insurrection": "a revolt; an uprising",
    "integrate": "to form, coordinate, or blend into a functioning or unified whole",
    "intend": "to have in mind as a purpose or goal",
    "intermittent": "off and on at a set inteval",
    "intuitive": "easy to use and figure out without directions",
    "inherent": "naturally occurring",
    "insolent": "insultingly contemptuous in speech or conduct",
    "invasive": "something that goes somewhere it isn't wanted",
    "inversion": "the act of turning upside down",
    "irk": "to annoy",
    "labyrinth": "amaze",
    "laden": "weighed down with something physically",
    "latter": "opposite of former; the second or last",
    "liaison": "a close connection or relationship; a person who facilitates understanding between parties",
    "magnitude": "how big something is",
    "malice": "the feeling of one person wishing to do something harmful to another person",
    "malign": "to say terrible things about someone",
    "manifest": "a complete list; to make appear, to make clear; obvious or clear",
    "manipulate": "to change something or someone to one's liking",
    "mantra": "something that people repeat over and over to themselves in the hopes that it becomes true or as a "
              "means toward achieving a goal",
    "marginalize": "the action of making something less, often when it shouldn't be",
    "mechanization": "when something that used to be done by hand is now done by a machine",
    "meddle": "to tamper with something, often human situations or emotions",
    "metastasize": "spreading",
    "mire": "to stick something down",
    "monotony": "the same thing over and over again",
    "motivation": "what drives someone",
    "mundane": "boring and normal",
    "mutable": "easy to or likely to change",
    "mystify": "to confuse",
    "net": "excluding all nonessential considerations",
    "notation": "something one writes to help one remember something or to convey information to another person",
    "nuance": "a subtle difference in the meaning or expression of something",
    "null": "nothing",
    "obliterate": "to completely and utterly destroy something beyond recognition",
    "obstinate": "refusing to give up even when wrong or faced with insurmountable forces against you",
    "oscillate": "to move back and forth in a predictable pattern at a set speed",
    "onerous": "something that is difficult to do, usually taking a lot of unpleasant work to complete",
    "panacea": "a fix-all solution",
    "parasitic": "attached to something else and feeds off of it without giving anything else",
    "parity": "equalness or being equal",
    "paradox": "something that contradicts itself or sets up an impossible train of thought that never ends but always"
               " circles back on itself",
    "partake": "to participate",
    "paternal": "to act in a fatherly way; relating to fathers",
    "permeate": "to soak through something, invading and saturating every part of it and leaving nothing untouched",
    "permutation": "an ordered arrangement of a set of objects",
    "perpetual": "never-ending",
    "perspective": "a mental view or prospect",
    "perturb": "to disturb in an emotional way",
    "pervade": "to become diffused through every part of",
    "phenomenon": "something that is known to exist or occur, the cause of which is often not clear",
    "pittance": "a pitiably small amount: not really enough to do anything with",
    "placticity": "the ability of something to change and be molded",
    "plenipotentiary": "a person who has been given the authority to act on behalf of their country in foreign "
                       "countries",
    "posterity": "the future of humankind: all of the people who will come in the future",
    "postulate": "to guess or to present an idea that is not proven",
    "potent": "very strong (not physically, but of a high concentration)",
    "prattle": "to talk on and on while saying little of value",
    "predecessor": "what came before something or someone",
    "preposterous": "so ridiculous as to be laughable",
    "primitive": "very basic and not technologically advanced",
    "pristine": "untouched and perfect",
    "proliferate": "to grow, spread, and reproduce, often at a high rate of speed",
    "promulgate": "to spread an idea around",
    "province": "a geographical area under a government",
    "proxy": "a substitute",
    "psychological": "of, relating to, or occuring in the mind",
    "quarrel": "to argue with someone; an argument",
    "rapacious": "unable to be satisfied",
    "receptive": "open to receiving things, often ideas",
    "redress": "to fix or make a situation right where someone has been wronged",
    "reluctant": "acting on the feeling of not wanting to do something",
    "remonstrate": "to object or speak out to something strongly",
    "repression": "the act of holding something down or back, especially ideas and movements",
    "reverence": "showing great respect or a deep appreciation for something",
    "rhetoric": "the way in which people speak and argue to convey their points",
    "sanction": "to officially approve or allow something to happen; to impose a penalty upon someone",
    "scuttling": "to move very quickly with tiny (often not smooth) steps",
    "scenario": "the setup for a work of fiction, a book, movie, or play",
    "seamless": "very smooth",
    "sentiment": "how someone feels or what someone says about something that has occurred",
    "sentinel": "a soldier whose job it is to keep watch over something",
    "sequence": "the order that things are in or should be in",
    "shingled": "covered with or as if with roof tiles",
    "skeptic": "someone who is doubtful of something",
    "sluggish": "moving like a slug",
    "squalid": "marked by filthiness and degredation from neglect or poverty",
    "squelch": "the sound that might be made if one tried to pull their foot out of thick mud",
    "stagnate": "to stop moving forward",
    "stewardship": "the act of taking care of something",
    "stupefied": "made temporarily stupid",
    "subjugate": "to put a person or group of people under one's total control",
    "subordinate": "lower in status, usually in a workplace",
    "subsequent": "following in time, order, or place",
    "substantial": "of an important size or amount",
    "sufficient": "enough",
    "supplemental": "serving to add something unneccessary but helpful to something else",
    "sustenence": "what sustains a person",
    "swayed": "fluctuating between one point, position, or opinion and another",
    "symmetric": "the same on both sides",
    "synthetic": "made artificially",
    "sullen": "grumpy and unethusiastic",
    "tactile": "of, relating to, or being the sense of touch",
    "tangible": "capable of being perceived, especially by the sense of touch",
    "tedious": "repetitive and boring",
    "tout": "to aggressively try to sell something; to sing something's praises to get someone to buy it",
    "transaction": "relating to the purchase or exchange of goods or services",
    "transit": "to move from one place to another; a network of public busses, trains, and streetcars",
    "traipse": "to come and go or to move in a carefree manner",
    "tributary": "a stream or river upstream that feeds into a big river",
    "ubiquitous": "found everywhere; common",
    "unassuming": "unthreatening and down to earth",
    "unrequited": "not returned in kind, especially feelings",
    "unseemly": "inappropraite for the situation",
    "unstinting": "given without pause or second thought",
    "unveil": "to reveal",
    "usurp": "to overthrow",
    "validate": "to say something is valid, true, or accurate",
    "vantage": "a spot with a good view to see what needs to be seen",
    "verifiable": "able to be proven correct",
    "vernacular": "the common or slang terms that people in a given community use",
    "versatile": "able to be used in many different ways",
    "vestigial": "remaining as the last small part of something that existed before",
    "virtuous": "having or exhibiting a high sense of morality",
    "wayside": "the side of a road or path",
    "yearning": "to want something with all your heart; to crave it at the expense of all else"}